apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-app
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 30001
      name: ssh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx_highforward
          imagePullPolicy: Never
          livenessProbe:
            tcpSocket:
              port: 30001
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1